name: 'Tests - Setup jq Action'

permissions: {}

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - 'action.yaml'
      - '.github/workflows/tests.yaml'
      - 'scripts/unixish.sh'
      - 'scripts/unixish-17.sh'
      - 'scripts/windowsish.ps1'
      - 'scripts/windowsish-17.ps1'

  pull_request:
    branches:
      - main

jobs:
  test-linux:
    strategy:
      matrix:
        image:
          - "ubuntu-22.04"
          - "ubuntu-20.04"
          - "macos-13"
          - "macos-11"
          - "macos-12"
          - "windows-2022"
          - "windows-2019"
        force:
          - 'true'
          - 'false'
        version:
          - '1.5'
          - '1.6'
          - '1.7'
    name: "Test Action - (img: ${{ matrix.image }}; version: ${{ matrix.version }}; force: ${{ matrix.force }})"
    runs-on: ${{ matrix.image }}
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Setup jq
        id: install-jq
        uses: ./
        with:
          version: '${{ matrix.version }}'
          force: '${{ matrix.force }}'

      - name: Check jq - Unix-ish
        if: (runner.os == 'Linux' || runner.os == 'macOS') && matrix.force == 'true'
        env:
          MATRIX_VERSION: ${{ matrix.version }}
        # language=sh
        run: |
          _err=
          _which="$(which jq)"
          _vers="$(jq --version)"
          if [[ "${_which}" != "$RUNNER_TOOL_CACHE/jq/jq" ]]; then
            echo "jq found at unexpected path."
            echo "  Expected:   \"$RUNNER_TOOL_CACHE/jq/jq\""
            echo "  Actual:     \"${_which}\""
            _err=1
          fi
          if [[ "${_vers}" != "jq-${MATRIX_VERSION}" ]]; then
            echo "jq --version returned unexpected value"
            echo "  Expected:   \"jq-${MATRIX_VERSION}\""
            echo "  Actual:     \"${_vers}\""
            _err=1
          fi
          if [ -n "${_err}" ]; then exit 1; fi;

      - name: Check Outputs - Unix-ish
        if: runner.os == 'Linux' || runner.os == 'macOS'
        env:
          MATRIX_FORCE: ${{ matrix.force }}
          OUTPUT_INSTALLED: ${{ steps.install-jq.outputs.installed }}
          OUTPUT_FOUND: ${{ steps.install-jq.outputs.found }}
        # language=sh
        run: |
          _installed="${OUTPUT_INSTALLED}"
          _err=
          if [[ "${MATRIX_FORCE}" == 'true' ]]; then
            # enabling "force" must result in an install
            if [[ "${OUTPUT_INSTALLED}" != 'true' ]]; then
              echo 'Unexpected value for "installed":'
              echo 'Expected:   "true"'
              echo "Actual:     \"${OUTPUT_INSTALLED}\""
              _err=1
            fi
          else
            if [[ "${OUTPUT_FOUND}" == 'true' ]]; then
              # if found, must not be installed without force
              if [[ "${OUTPUT_INSTALLED}" != 'false' ]]; then
                echo 'Unexpected value for "installed":'
                echo 'Expected:   "false"'
                echo "Actual:     \"${OUTPUT_INSTALLED}\""
                _err=1
              fi
            else
              # if not found, must be installed
              if [[ "${OUTPUT_INSTALLED}" != 'true' ]]; then
                echo 'Unexpected value for "installed":'
                echo 'Expected:   "true"'
                echo "Actual:     \"${OUTPUT_INSTALLED}\""
                _err=1
              fi
            fi
          fi
          if [ -n "${_err}" ]; then exit 1; fi;
          

      - name: Check jq - Windows-ish
        if: runner.os == 'Windows' && matrix.force == 'true'
        env:
          MATRIX_VERSION: ${{ matrix.version }}
        # language=powershell
        run: |
          Get-Command "jq.exe"
          $_cmd={jq.exe --version }
          $_vers=jq.exe --version 2>&1
          if ( "${_vers}" -ne "jq-$Env:MATRIX_VERSION" -and "${_vers}" -ne "jq-$Env:MATRIX_VERSION-dirty" )
          {
              Write-Host "jq.exe --version returned unexpected value"
              Write-Host "  Expected:   jq-$Env:MATRIX_VERSION"
              Write-Host "  Actual:     ${_vers}"
              exit 1
          }

      - name: Check Outputs - Windows-ish
        if: runner.os == 'Windows'
        shell: powershell
        env:
          MATRIX_FORCE: ${{ matrix.force }}
          OUTPUT_INSTALLED: ${{ steps.install-jq.outputs.installed }}
          OUTPUT_FOUND: ${{ steps.install-jq.outputs.found }}
        # language=powershell
        run: |
          $ErrorActionPreference = 'Stop'
          Set-StrictMode -Version Latest
          $_installed=$Env:OUTPUT_INSTALLED
          $_err = 0
          if ($Env:MATRIX_FORCE -eq "true")
          {
              # enabling "force" must result in an install
              if ($Env:OUTPUT_INSTALLED -ne "true")
              {
                  Write-Host "Unexpected value for installed"
                  Write-Host "Expected:   true"
                  Write-Host "Actual:     $Env:OUTPUT_INSTALLED"
                  $_err=1
              }
          }
          else
          {
              if ($Env:OUTPUT_FOUND -eq "true")
              {
                  # if found, must not be installed without force
                  if ($Env:OUTPUT_INSTALLED -ne "false")
                  {
                      Write-Host "Unexpected value for installed"
                      Write-Host "Expected:  false"
                      Write-Host "Actual:    $Env:OUTPUT_INSTALLED"
                      $_err=1
                  }
              }
              else
              {
                  # if not found, must be installed
                  if ($Env:OUTPUT_INSTALLED -ne "true") {
                      Write-Host "Unexpected value for installed"
                      Write-Host "Expected:  true"
                      Write-Host "Actual:    $Env:OUTPUT_INSTALLED"
                      $_err=1
                  }
              }
          }
          if ("${_err}" -ne 0)
          {
              exit 1
          }
  test-container:
    strategy:
      matrix:
        image:
          - "ubuntu-22.04"
          - "ubuntu-20.04"
        force:
          - 'true'
          - 'false'
        version:
          - '1.5'
          - '1.6'
          - '1.7'
    name: "Test Action (Container) - (img: ${{ matrix.image }}; version: ${{ matrix.version }}; force: ${{ matrix.force }})"
    runs-on: ${{ matrix.image }}
    container:
      image: node:18.12.1
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Setup jq
        id: install-jq
        uses: ./
        with:
          version: '${{ matrix.version }}'
          force: '${{ matrix.force }}'

      - name: Check jq
        env:
          MATRIX_VERSION: ${{ matrix.version }}
        # language=sh
        run: |
          _err=
          _which="$(which jq)"
          _vers="$(jq --version)"
          if [[ "${_which}" != "$RUNNER_TOOL_CACHE/jq/jq" ]]; then
            echo "jq found at unexpected path."
            echo "  Expected:   \"$RUNNER_TOOL_CACHE/jq/jq\""
            echo "  Actual:     \"${_which}\""
            _err=1
          fi
          if [[ "${_vers}" != "jq-${MATRIX_VERSION}" ]]; then
            echo "jq --version returned unexpected value"
            echo "  Expected:   \"jq-${MATRIX_VERSION}\""
            echo "  Actual:     \"${_vers}\""
            _err=1
          fi
          if [ -n "${_err}" ]; then exit 1; fi;

      - name: Check Outputs
        env:
          MATRIX_FORCE: ${{ matrix.force }}
          OUTPUT_INSTALLED: ${{ steps.install-jq.outputs.installed }}
          OUTPUT_FOUND: ${{ steps.install-jq.outputs.found }}
        # language=sh
        run: |
          _installed="${OUTPUT_INSTALLED}"
          _err=
          if [[ "${MATRIX_FORCE}" == 'true' ]]; then
            # enabling "force" must result in an install
            if [[ "${OUTPUT_INSTALLED}" != 'true' ]]; then
              echo 'Unexpected value for "installed":'
              echo 'Expected:   "true"'
              echo "Actual:     \"${OUTPUT_INSTALLED}\""
              _err=1
            fi
          else
            if [[ "${OUTPUT_FOUND}" == 'true' ]]; then
              # if found, must not be installed without force
              if [[ "${OUTPUT_INSTALLED}" != 'false' ]]; then
                echo 'Unexpected value for "installed":'
                echo 'Expected:   "false"'
                echo "Actual:     \"${OUTPUT_INSTALLED}\""
                _err=1
              fi
            else
              # if not found, must be installed
              if [[ "${OUTPUT_INSTALLED}" != 'true' ]]; then
                echo 'Unexpected value for "installed":'
                echo 'Expected:   "true"'
                echo "Actual:     \"${OUTPUT_INSTALLED}\""
                _err=1
              fi
            fi
          fi
          if [ -n "${_err}" ]; then exit 1; fi;
